export const ANNOUNCEMENTS_ERROR_NOT_FOUND = "Announcement not found!";
export const ANNOUNCEMENTS_ERROR_CANT_UPDATE_SENDING =
  "You can't update this announcement since this is already sending!";
export enum ANNOUNCEMENTS_STATUS {
  DRAFT = "DRAFT",
  PENDING = "PENDING",
  SENDING = "SENDING",
  SENT = "SENT",
  CANCELLED = "CANCELLED",
}
export enum ANNOUNCEMENT_AUDIENCE_TYPE {
  EMPLOYEE = "EMPLOYEE",
  PRIMARY_SCHOOL = "PRIMARY_SCHOOL",
  JUNIOR_HIGH_SCHOOL = "JUNIOR_HIGH_SCHOOL",
  SENIOR_HIGH_SCHOOL = "SENIOR_HIGH_SCHOOL",
  COLLEGE = "COLLEGE",
}

export enum ANNOUNCEMENT_AUDIENCE_MODE {
  SEND_TO_ALL = "SEND_TO_ALL",
  SEND_TO_ONE = "SEND_TO_ONE",
  SEND_TO_MANY = "SEND_TO_MANY",
}

export enum ANNOUNCEMENT_ACTIONS {
  DRAFT = "DRAFT",
  SEND = "SEND",
}

export enum TARGET_RECIPIENT_TYPE {
  STUDENT = "STUDENT",
  EMPLOYEE = "EMPLOYEE",
}