export enum JOB_TYPE {
  ANNOUNCEMENTS_SENDER = "ANNOUNCEMENTS_SENDER",
  LINK_REQUEST_PENDING_REMINDER = "LINK_REQUEST_PENDING_REMINDER",
}

export enum JOB_STATUS {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}